### ISSUE TITLE
AttributeError: 'Listener' object has no attribute 'add'

### ISSUE THREAD

**Issue by calingasankj** [Catalyst4222/interactions-wait-for#10]
I tried using the standard code for wait_for in the Readme, and it resulted in the error above.

On a related note, wait_for_components isn't working either but the error it displays is that the module doesn't exist.

**Comment by sillyElvy** [comment]
Make sure to run `setup(bot)` in your code

**Comment by calingasankj** [comment]
thank you for that! what about this error: Unknown interaction, with code '10062' and severity '40'?

**Comment by sillyElvy** [comment]
> thank you for that! what about this error: Unknown interaction, with code '10062' and severity '40'?

It means that you responded with ctx.send too late, I recommend joining the [support server](https://discord.gg/interactions) for those kind of questions instead of using an issue

**Comment by calingasankj** [comment]
copy that, Thank you so much for all your help. i was able to solve it after your last message too! works fine now <3

**Comment by sillyElvy** [comment]
Alright, closing this then
