### ISSUE TITLE
TypeError: Extension.__new__() missing 1 required positional argument: 'client'

### ISSUE THREAD

**Issue by FuckingToasters** [Catalyst4222/interactions-wait-for#11]
This error always happen when selecting a item from the payment selection menu:
```py
[]
<bound method paymentclass.duration of <cogs.payment.paymentclass object at 0x7f50651c1300>>
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<paymentclass.selectpm() done, defined at /home/infinimonster/Documents/Privat/Python/infiniproxy bot/payment bot/cogs/payment.py:280> exception=TypeError("Extension.__new__() missing 1 required positional argument: 'client'")>
Traceback (most recent call last):
  File "/home/infinimonster/Documents/Privat/Python/infiniproxy bot/payment bot/cogs/payment.py", line 300, in selectpm
    embed = interactions.Embed(
  File "/home/infinimonster/.local/lib/python3.10/site-packages/interactions/utils/attrs_utils.py", line 30, in __init__
    kwargs = deepcopy(kwargs)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 238, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.10/copyreg.py", line 101, in __newobj__
    return cls.__new__(cls, *args)
TypeError: Extension.__new__() missing 1 required positional argument: 'client'
```

```py
    @interactions.extension_component("payment")
    async def selectpm(self, ctx: interactions.ComponentContext, cryptodata: list):
        self.cryptodata = cryptodata[0]
        if self.cryptodata == "Bitcoin":
            self.sym = "BTC"

        elif self.cryptodata == "Ethereum":
            self.sym = "ETH"
        
        elif self.cryptodata == "Litecoin":
            self.sym = "LTC"
        
        elif self.cryptodata == "Dashcoin":
            self.sym = "DASH"

        print(self.ctxvalues)
        if self.ctxvalues == ["day"]: self.duration = "Daily"
        elif self.ctxvalues == ["week"]: self.duration = "Weekly"
        elif self.ctxvalues == ["month"]: self.duration = "Monthly"
        print(self.duration)
        embed = interactions.Embed(
            color=self.Pink,
            author=interactions.EmbedAuthor(name=f"Confirmation", icon_url=self.Thumbnail),
            description="Do you want to place this Order? Order Details below.",
            fields=[
                interactions.EmbedField(name="Product", value=self.productlabel[self.productdata], inline=False),
                interactions.EmbedField(name="Duration", value=self.duration, inline=False),
                interactions.EmbedField(name="Price", value=f"{self.price}€", inline=False),
                interactions.EmbedField(name="Payment Method", value=self.cryptodata, inline=False)
                ],
            thumbnail=interactions.EmbedImageStruct(url=self.Thumbnail),
            footer=interactions.EmbedFooter(text=self.Watermark)
            )
        # self.buttonconfirm.disabled = True
        # self.buttoncancel.disabled = True
        await ctx.send(embeds=embed, components=[self.confirmrow, self.cancelrow], ephemeral=True)
```

as you might have noticed, it print a empty list before the Traceback happen, The list is set to empty in the init function and later changed to the duration value (["day"] ["week"] ["month"]) so it is weird tht after the content has changed and i print it in the code above, it is a empty list again.

I also tried to change the embed content because i thought that the issue might be the empty list it's sending but the error were the same,

I'm asking this Question here and not on the official repo because the error seem to happen from a extension and the only extension i'm using is this one.

Hopefully someone can help me out,
Regards FuckingToasters,

**Comment by mAxYoLo01** [comment]
Hello, please use the official support for that question. Also, I believe we need more information on the whole class.

**Comment by sillyElvy** [comment]
> This error always happen when selecting a item from the payment selection menu:
> ```py
> []
> <bound method paymentclass.duration of <cogs.payment.paymentclass object at 0x7f50651c1300>>
> Task exception was never retrieved
> future: <Task finished name='Task-40' coro=<paymentclass.selectpm() done, defined at /home/infinimonster/Documents/Privat/Python/infiniproxy bot/payment bot/cogs/payment.py:280> exception=TypeError("Extension.__new__() missing 1 required positional argument: 'client'")>
> Traceback (most recent call last):
>   File "/home/infinimonster/Documents/Privat/Python/infiniproxy bot/payment bot/cogs/payment.py", line 300, in selectpm
>     embed = interactions.Embed(
>   File "/home/infinimonster/.local/lib/python3.10/site-packages/interactions/utils/attrs_utils.py", line 30, in __init__
>     kwargs = deepcopy(kwargs)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 206, in _deepcopy_list
>     append(deepcopy(a, memo))
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
>     y = [deepcopy(a, memo) for a in x]
>   File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
>     y = [deepcopy(a, memo) for a in x]
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 238, in _deepcopy_method
>     return type(x)(x.__func__, deepcopy(x.__self__, memo))
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
>     y = func(*args)
>   File "/usr/lib/python3.10/copyreg.py", line 101, in __newobj__
>     return cls.__new__(cls, *args)
> TypeError: Extension.__new__() missing 1 required positional argument: 'client'
> ```
> 
> ```py
>     @interactions.extension_component("payment")
>     async def selectpm(self, ctx: interactions.ComponentContext, cryptodata: list):
>         self.cryptodata = cryptodata[0]
>         if self.cryptodata == "Bitcoin":
>             self.sym = "BTC"
> 
>         elif self.cryptodata == "Ethereum":
>             self.sym = "ETH"
>         
>         elif self.cryptodata == "Litecoin":
>             self.sym = "LTC"
>         
>         elif self.cryptodata == "Dashcoin":
>             self.sym = "DASH"
> 
>         print(self.ctxvalues)
>         if self.ctxvalues == ["day"]: self.duration = "Daily"
>         elif self.ctxvalues == ["week"]: self.duration = "Weekly"
>         elif self.ctxvalues == ["month"]: self.duration = "Monthly"
>         print(self.duration)
>         embed = interactions.Embed(
>             color=self.Pink,
>             author=interactions.EmbedAuthor(name=f"Confirmation", icon_url=self.Thumbnail),
>             description="Do you want to place this Order? Order Details below.",
>             fields=[
>                 interactions.EmbedField(name="Product", value=self.productlabel[self.productdata], inline=False),
>                 interactions.EmbedField(name="Duration", value=self.duration, inline=False),
>                 interactions.EmbedField(name="Price", value=f"{self.price}€", inline=False),
>                 interactions.EmbedField(name="Payment Method", value=self.cryptodata, inline=False)
>                 ],
>             thumbnail=interactions.EmbedImageStruct(url=self.Thumbnail),
>             footer=interactions.EmbedFooter(text=self.Watermark)
>             )
>         # self.buttonconfirm.disabled = True
>         # self.buttoncancel.disabled = True
>         await ctx.send(embeds=embed, components=[self.confirmrow, self.cancelrow], ephemeral=True)
> ```
> 
> as you might have noticed, it print a empty list before the Traceback happen, The list is set to empty in the init function and later changed to the duration value (["day"] ["week"] ["month"]) so it is weird tht after the content has changed and i print it in the code above, it is a empty list again.
> 
> I also tried to change the embed content because i thought that the issue might be the empty list it's sending but the error were the same,
> 
> I'm asking this Question here and not on the official repo because the error seem to happen from a extension and the only extension i'm using is this one.
> 
> 
> Hopefully someone can help me out,
> Regards FuckingToasters,

To bring clarity on this: It is saying extension because you are using a cog. And in our library you do that by subclassing from `Extension`.

So as already said, please open this as an issue on the main repository. Additionally you have to provide the whole cog because finding the root of the issue will be difficult otherwise. Also, make sure that you use the latest version as this might have already been fixed.
